[package]
name = "nobuildlitter"
version = "0.1.0"
authors = ["Andrew Gaul <andrew@gaul.org>"]
edition = "2018"

[dependencies]
libc = "0.2.66"
redhook = "1.0.0"

[lib]
name = "nobuildlitter"
crate_type = ["dylib"]
